### ISSUE TITLE
Why is botToken necessary for addMember?

### ISSUE THREAD

**Issue by EmptyCrown** [reboxer/discord-oauth2#11]
Hey there, I was looking through the docs here https://discordapp.com/developers/docs/resources/guild#add-guild-member and I don't quite see why a botToken is needed for the `addMember` command? I created a new bot in my app and copied in the token, but I'm consistently getting `403` errors. I've made sure that `guilds.join` is in the scope.

**Comment by EmptyCrown** [comment]
Nevermind -- resolved!

**Comment by sexboobieshd** [comment]
Sorry for necropost, but how did you fix the error? I'm having the same issue.
