### ISSUE TITLE
Missing Refresh Token Request

### ISSUE THREAD

**Issue by HeyItsNewbie** [reboxer/discord-oauth2#12]
Just want to say thanks for library, saved some time writing one :-)

Just as an FYI, you need a refresh token call or allow the tokenRequest to also be used for refreshing tokens. Currently it can't be as it's expecting a code attribute when called, which the Discord OAuth2 refresh token call doesn't require.

Cheers
Shane.

**Comment by reboxer** [comment]
Thanks for letting me know!
I've just published [v2.1.0](https://github.com/reboxer/discord-oauth2/releases/tag/v2.1.0) fixing this.
