### ISSUE TITLE
try catch doesn't work

### ISSUE THREAD

**Issue by willuhm-js** [reboxer/discord-oauth2#15]
I am trying to handle errors, and try catch blocks aren't working around the code, instead it just returns the error, as if it's ignoring my try/catch blocks..

**Comment by reboxer** [comment]
Since all functions return a promise (except `generateAuthURL`), it's very likely that you are not `await`ing the funcion call inside your `try` blocks, which the `catch` block won't catch.

If this is not the case, please provide your node version, package version and code to reproduce this issue.

**Comment by reboxer** [comment]
im closing this as there hasn't been any response in one week, if you still need help, you are welcome to open an issue.
