### ISSUE TITLE
400 Bad Request on POST /api/v7/oauth2/token

### ISSUE THREAD

**Issue by PartTimeJS** [reboxer/discord-oauth2#16]
Getting the following when trying to request a token:

(node:31264) UnhandledPromiseRejectionWarning: DiscordHTTPError: 400 Bad Request on POST /api/v7/oauth2/token
     at OAuth.request (/var/www/html/OklahomaCity/PHP-Oauth/node_modules/discord-oauth2/lib/eris/rest/RequestHandler.js:91:15)
     at OAuth.tokenRequest (/var/www/html/OklahomaCity/PHP-Oauth/node_modules/discord-oauth2/lib/OAuth.js:44:21)
     at /var/www/html/OklahomaCity/PHP-Oauth/wall.js:122:11
     at Layer.handle [as handle_request] (/var/www/html/OklahomaCity/PHP-Oauth/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/OklahomaCity/PHP-Oauth/node_modules/express/lib/router/route.js:137:13)
     at Route.dispatch (/var/www/html/OklahomaCity/PHP-Oauth/node_modules/express/lib/router/route.js:112:3)
     at Layer.handle [as handle_request] (/var/www/html/OklahomaCity/PHP-Oauth/node_modules/express/lib/router/layer.js:95:5)
     at /var/www/html/OklahomaCity/PHP-Oauth/node_modules/express/lib/router/index.js:281:22
     at Function.process_params (/var/www/html/OklahomaCity/PHP-Oauth/node_modules/express/lib/router/index.js:335:12)
     at next (/var/www/html/OklahomaCity/PHP-Oauth/node_modules/express/lib/router/index.js:275:10)

**Comment by reboxer** [comment]
From that stack trace alone is not possible to know exactly what went wrong, either the redirect code you provided is wrong, or some other parameter you passed are wrong.
You can see the error discord sent by looking at the `response` property and the errors provided.

**Comment by aRkker** [comment]
I have this exact same issue happening. The error is the dreaded 'invalid_grant' that Discord likes to give you

**Comment by reboxer** [comment]
Could you both @aRkker and @PartTimeJS provide the code snippet which you are having issues with?

**Comment by aRkker** [comment]
> Could you both @aRkker and @PartTimeJS provide the code snippet which you are having issues with?

```js
const CLIENT_SECRET = '<client secret here>';
const CLIENT_ID = '<client id here>';
const creds = btoa(`${CLIENT_ID}:${CLIENT_SECRET}`);
const redirect = 'http://localhost:9910/discord/callback'; // this is a whitelisted redirect url on the app's settings for testing

const DiscordOauth2 = require("discord-oauth2");
const oauth = new DiscordOauth2({
    clientSecret: CLIENT_SECRET,
    clientId: CLIENT_ID,
    redirectUri: redirect,
    credentials: creds
})
```

Then later, inside a handler function for the specific route in Express:

```js
const response = await oauth.tokenRequest({        
     code: request.query.code, // Verified this does exist
     grantType: 'authorization_code',

})
```

I'm not sure if its any help, but up until today my own manual request implementation worked. It was only today that a user came to me saying it doesn't work, and I haven't changed anything regarding it. Perhaps something has changed on Discord's side?

**Comment by PartTimeJS** [comment]
> 
> 
> Could you both @aRkker and @PartTimeJS provide the code snippet which you are having issues with?

I fixed it. I stopped using this module and just used an axios request and sent the data as a string in the body instead of in the URL. I talked to some guys on the Discord API discord.

here's the code that should fix your issue:
```
      let data = `client_id=${oauth2.client_id}&client_secret=${oauth2.client_secret}&grant_type=authorization_code&code=${code}&redirect_uri=${config.redirect_url}&scope=${oauth2.scope}`;
      let headers = {
        'Content-Type': 'application/x-www-form-urlencoded',
      }
      axios.post("https://discord.com/api/oauth2/token", data, {
        headers: headers
      }).then(async function(response) {
        return resolve(response.data);
      }).catch(error => {
        console.error("[Oauth2+Stripe] [oauth2.js]", error.response);
        return resolve(error);
      });
    });
```

**Comment by reboxer** [comment]
@aRkker your code seems to work completely fine for me, what node and package version are you using?

**Comment by aRkker** [comment]
@reboxer node `12.14.0` and `"discord-oauth2": "^2.2.0",`

**Comment by aRkker** [comment]
On a further note, I created a new project from scratch on Discord's developer portal and hooked up the module to it, and that works. I'm guessing somethings wrong with either the project or one of the parameters

**Comment by reboxer** [comment]
Sorry @aRkker but i can't seem to reproduce your error with all the info you provided, `invalid_grant` generally means that the data isn't being sent correctly and the API doesn't catch that first parameter, but i can't see any issues with how the library does the request, and it seems weird that one of your applications works but the other doesn't.
You could PartTimeJS' approach and see if that works, or try going to https://discord.gg/discord-api and see if they can help you.

On a side note, @PartTimeJS this module sends the querystring in the body, not on the URL.

**Comment by zapdos26** [comment]
I also encountered this bug today too. I did not change any of the code relating to Discord in the past couple days. It does appear that it is due to Discord fixing a bug based on the discussions in the  Discord API guild.

**Comment by SkayuX** [comment]
Hi, I'm having a similar issue, I'm sure I have everything set up, but still getting the issue

```
oauth.tokenRequest({
        clientId: "clientid",
        clientSecret: "clientsecret",
    
        code: req.query.code,
        scope: "identify guilds",
        grantType: "authorization_code",
        
        redirectUri: "http://localhost:5000/callback",
    }).then(console.log)
```

**Comment by reboxer** [comment]
> Hi, I'm having a similar issue, I'm sure I have everything set up, but still getting the issue
> 
> ```
> oauth.tokenRequest({
>         clientId: "clientid",
>         clientSecret: "clientsecret",
>     
>         code: req.query.code,
>         scope: "identify guilds",
>         grantType: "authorization_code",
>         
>         redirectUri: "http://localhost:5000/callback",
>     }).then(console.log)
> ```

Please don't necrobump a 7 months old issue. Follow the template and open a new one.
