### ISSUE TITLE
Must NOT urlEncode -- update README?

### ISSUE THREAD

**Issue by dylanh724** [reboxer/discord-oauth2#19]
If you url encode your `redirectUri`, you get this:

`DiscordRESTError [50035]: DiscordRESTError [50035]: Invalid Form Body redirect_uri: Not a well formed URL.`

Perhaps readme should be updated? The average person likely encodes. This was a bit confusing ~

**Comment by reboxer** [comment]
This is not necessary, If you look at the description of the property in the README, it's not specified that you must encode the `redirectUri` and in the examples none of the properties are being manually `encodeURIComponent`'d, so you should not assume that you must encode it (and it wouldn't make much sense to put examples that are supposed to work that actually don't)
