### ISSUE TITLE
Adding missing parameters to addMember

### ISSUE THREAD

**Issue by TheLetslook** [reboxer/discord-oauth2#2]
Hello, could you add the missing parameters (nick, roles, mute and deaf) to the addMember function? 
[Reference](https://discordapp.com/developers/docs/resources/guild#add-guild-member)

**Comment by reboxer** [comment]
Thanks for opening this issue! This was added in [1.4.0](https://github.com/reboxer/discord-oauth2/releases/tag/v1.4.0) and it's already published on npm.
