### ISSUE TITLE
Http 400

### ISSUE THREAD

**Issue by SS4PPHIRE** [reboxer/discord-oauth2#29]
I'm getting an error when trying to do tokenRequest().

(node:1405) UnhandledPromiseRejectionWarning: DiscordHTTPError: 400 Bad Request on POST /api/v7/oauth2/token

**Comment by reboxer** [comment]
Sorry, but i can't help you if you don't provide the code you are using to get this error.

**Comment by SS4PPHIRE** [comment]
Sorry. Forgot about that. I just copied it from the example.

`const DiscordOauth2 = require("discord-oauth2");
const oauth = new DiscordOauth2();

oauth.tokenRequest({
	clientId: "botclientid",
	clientSecret: "botclientsecret",

	code: "query code",
	scope: "identify guilds",
	grantType: "authorization_code",
	
	redirectUri: "https://discord.com",
}).then(console.log)`

I replaced the clientId and clientSecret with the ones from my application.

**Comment by CA1R7** [comment]
@SS4PPHIRE  it's working with me, try a new request.

**Comment by CA1R7** [comment]
@reboxer  i wanna get email i have been add it on scopes but Nothing at the result how?

**Comment by OKman65** [comment]
I had this error when I didn't have the `Host` parameter in the Headers, maybe I should add this parameter to the module requests?

I also got this from there: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host

**Comment by SS4PPHIRE** [comment]
What do you mean by "try a new login for request new code"

**Comment by reboxer** [comment]
@CA1R7 This is not the place to ask, read the [discord oauth2](https://discord.com/developers/docs/topics/oauth2) documentation for that.

@SS4PPHIRE Unless you own discord's domain and host your app there, you can't set `redirectUri` to `"https://discord.com"`, you have to set it to the exact same uri (domain you own + the path you are using to handle the redirect) you've set in your application.

**Comment by CA1R7** [comment]
@reboxer  uh thank you
