### ISSUE TITLE
Something strange when trying to authorize user

### ISSUE THREAD

**Issue by B1logic** [reboxer/discord-oauth2#36]
When I redirect user to generated authorize URL then this shows up - [Picture](https://imgur.com/a/lkG71n9)

My code:
```
const scopes = "identify email guilds rpc activities.read activities.write";

const url = oauth.generateAuthUrl({
    scope: scopes,
    responseType: "code"
});
    
console.log("generated_Auth_url: ", url); // https://discord.com/api/oauth2/authorize?client_id=766864585285304351&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fdiscord%2Fcallback&response_type=code&scope=identity%20email%20guilds%20rpc%20activities.read%20activities.write
res.redirect(url);
```

**Comment by B1logic** [comment]
Just checked that url from discord oauth2 authorize link generator is same as the URL from generateAuthUrl() but when I redirect user to this user the problem appears.

**Comment by reboxer** [comment]
I tried your code and it works fine, you must be doing something weird. That URL you put as a comment doesn't work because the "identity" scope doesn't exist, and the library is definetely not the one at fault.
