### ISSUE TITLE
401 Unauthorized on getUserGuilds

### ISSUE THREAD

**Issue by FoglyOgly** [reboxer/discord-oauth2#4]
I'm able to get a valid access token, but getUserGuilds is throwing 401 Unauthorized anyway. Any suggestions?

**Comment by reboxer** [comment]
There are a few reasons i can think of on why it returns a 401, either the user revoked the application's access, the user didn't authorize the application with the `guilds` scope, or in the token request you forgot to add `guilds` in the scope parameter, make sure you are using the `guilds` scope in your OAuth link and are passing `guilds` in the token request aswell.
You should be able to log `error.response` to see the error discord is sendig you.

**Comment by reboxer** [comment]
@FoglyOgly were you able to figure out what your issue was?
