### ISSUE TITLE
DiscordHTTPError: 401 Unauthorized on GET /api/v7/users/@me/guilds while using oauth.getUserGuilds()

### ISSUE THREAD

**Issue by Bluppie05** [reboxer/discord-oauth2#40]
**Describe the error**
I'm getting this error when running oauth.getUserGuilds, the token is already harvested from the code via oauth.tokenRequest, though the token is not working while using oauth.getUserGuilds, can anyone help me?

**NodeJS version**
*v14.15.0*

**callback code**
```js
router.get('/callback', catchAsync(async (req, res) => {
  const code = req.query.code;
  oauth.tokenRequest({
    clientId: `${CLIENT_ID}`,
    clientSecret: `${CLIENT_SECRET}`,
  
    code: code,
    scope: "identify guilds",
    grantType: "authorization_code",
    
    redirectUri: 'REDIRECT URL',
  }).then((result) => {
    console.log(result.access_token)
    res.render('post.html', {token:result.access_token});
  });
  //console.log(token)
}));
```
**Get userguilds code**
```js
// note, req.session.token is set earlier by the code and verified working

app.get('/guilds', function (req, res) {
	console.log("guild page loaded")
	console.log(`user access token: ${req.session.token}`)
	oauth.getUserGuilds(req.session.token).then((userresult) => {
		if (err) throw err;
		console.log(userresult);
	});
});
```

Edit: I just tried using the same access token to do oauth.getUser() and it did work, it seems to only occur using oauth.getUserGuilds()

**Comment by Suessgott** [comment]
Had the same problem. I realised just now that I only used the Identify scope. For getUserGuilds you need the guilds scope as well.

**Comment by Bluppie05** [comment]
> Had the same problem. I realised just now that I only used the Identify scope. For getUserGuilds you need the guilds scope as well.

I discovered this aswell that it wasn't properly asking for guild permissions, I fixed this, however, it still did not fix my issue

**Comment by Bluppie05** [comment]
ah wait, I don't know how that fixed it but I just removed the ```if (err) throw err;``` part and now it's working, thanks for everyone that helped me and I'm glad this issue is fixed, I'll close the issue after I do a bit of testing
