### ISSUE TITLE
Token Request does not work on iPhone Chrome

### ISSUE THREAD

**Issue by GoalPanda** [reboxer/discord-oauth2#43]
Hi, I have already built a site that uses discord OAuth.
That site is working well on laptop chrome browsers and also android phone chrome browsers.
But only on iPhone chrome browsers, it does not work.
Especially, 

const **token_res** = await oauth.tokenRequest({ ... })
const user = await oauth.getUser(token_res.**access_token**)
...

does not work.
Please help me.

**Comment by reboxer** [comment]
If it works in some browsers but one, then that's an issue related to the browser and not the library. Also keep in mind that if you are using the library directly in the browser and not in a node application, support will not be provided as the library is not meant to be used in a browser.
