### ISSUE TITLE
Very high latency, Can also have issuses with timeouts.

### ISSUE THREAD

**Issue by HyperDev6969** [reboxer/discord-oauth2#44]
**Describe the error**
A lot of the time it is very slow to load/get from the oauth2 API. Even sometimes timing out.

**NodeJS version**
14.14.0

**Relevant code**
```js
oauth.getUser(token).then((user) => {
        oauth.getUserGuilds(token).then((guild) => {
        
        });
});
```
![image](https://user-images.githubusercontent.com/70071615/102257882-9745f080-3f0d-11eb-99b8-e23346f8ae9f.png)
The time to get info for me is between 1 - 5 seconds on average. Sometimes it is just way over that. I cant make a good dashboard with it being this slow.

Have a nice day!
~HyperDev

**Comment by reboxer** [comment]
This highly likely has nothing to do with the library itself, google and discord have been having issues lately. Requests timing out means that the discord API is taking too long to reply and the library automatically aborts them after whaterver you set it to (default is 15 seconds), if you want to raise this limit see the requestTimeout option in the [class constructor](https://github.com/reboxer/discord-oauth2#options).
