### ISSUE TITLE
Bad request on POST

### ISSUE THREAD

**Issue by aerglos** [reboxer/discord-oauth2#46]
**Describe the error**
 DiscordHTTPError: 400 Bad Request on POST /api/v8/oauth2/token

**NodeJS version**
Latest

**Relevant code**
```js
import DiscordOAuth2 from "discord-oauth2";

export default function handler(req, res) {
    const oauth = new DiscordOAuth2({
        version: 'v8'
    });
    oauth.tokenRequest({
        clientId: "<valid id>",
        clientSecret: "<valid secret>",

        code: req.query.code,
        scope: "identify",
        grantType: "authorization_code",

    }).then(console.log)
    console.log(req.query.code)
    res.redirect('/tools/view/forms');

}
```

So in this NextJS API handler, I've observed that the req,query.code is valid, but when it tries to log the tokenRequest it gives me the error `DiscordHTTPError: 400 Bad Request on POST /api/v8/oauth2/token`

Even if I set the response type to token in the actual URL, it gives me a bad request on GET error. What is the issue with the bad requests?

**Comment by reboxer** [comment]
Your request is missing the `redirectUri` parameter.

**Comment by WickedWizard3588** [comment]
But, I have everything correct and this error pops up 
```js
const router = require('express').Router();
const oauth2 = require('discord-oauth2');
const oauth = new oauth2();
const { client_id, client_secret } = require('../../config.json');

router.get('/discord', (req, res) => {
    oauth.tokenRequest({
        clientId: client_id,
        clientSecret: client_secret,
        scope: ['identify', 'guilds'],
        redirectUri: 'http://localhost:8080/api/auth/test',
        grantType: 'authorization_code',
        code: req.query.code,
    }).then((resu) => {
        console.log(resu);
        res.send(resu);
    });
});

router.get('/test', (req, res) => res.sendStatus(200));

module.exports = router;
```

**Comment by reboxer** [comment]
> But, I have everything correct and this error pops up
> 
> ```js
> const router = require('express').Router();
> const oauth2 = require('discord-oauth2');
> const oauth = new oauth2();
> const { client_id, client_secret } = require('../../config.json');
> 
> router.get('/discord', (req, res) => {
>     oauth.tokenRequest({
>         clientId: client_id,
>         clientSecret: client_secret,
>         scope: ['identify', 'guilds'],
>         redirectUri: 'http://localhost:8080/api/auth/test',
>         grantType: 'authorization_code',
>         code: req.query.code,
>     }).then((resu) => {
>         console.log(resu);
>         res.send(resu);
>     });
> });
> 
> router.get('/test', (req, res) => res.sendStatus(200));
> 
> module.exports = router;
> ```

The `redirectUri` on the request must match the `redirectUri` you set in  your application's settings and the OAuth URL.
If you want to use the `/discord` route, you must set it as `redirectUri` in your application's OAuth2 settings and in the OAuth URL.

```js
router.get('/discord', (req, res) => {
    oauth.tokenRequest({
        ...
        redirectUri: 'http://localhost:8080/discord',
        ...
    }).then((resu) => {
        console.log(resu);
        res.send(resu);
    });
});
```

![chrome_N8kawfHpKf](https://user-images.githubusercontent.com/7484116/112501803-4f363580-8d68-11eb-86dd-5d1470a1da9c.png)
![image](https://user-images.githubusercontent.com/7484116/112503375-9e309a80-8d69-11eb-93f3-0b1b7105b895.png)

**Comment by WickedWizard3588** [comment]
Yes, I have that redirect uri put up in the Dev Portal
