### ISSUE TITLE
Rename OAuth to DiscordAuth

### ISSUE THREAD

**Issue by antoine-pous** [reboxer/discord-oauth2#47]
Actually your class name is not relevant and can be in conflict with more generic packages. Your package manage only Discord auth, then `DiscordAuth` would be more relevant than `OAuth`.

**Comment by reboxer** [comment]
If you are talking about the code in the `index.js` file, last time i checked whatever you name your variables doesn't interfere with other file/modules/packages and it's completely irrelevant.
