### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by janmitrovic** [reboxer/discord-oauth2#5]
Hello,

when I push my express react discord auth website on server (Ubuntu) I get error. Module is installed btw.
![7B4306A3-2D7E-4528-B8CD-20B561FBC7C7](https://user-images.githubusercontent.com/16691884/70429608-37567780-1a79-11ea-9694-8bf400dba164.png)

**Comment by janmitrovic** [comment]
And it works on local computer. Can attach code if needed but module is called as suggested in documentation.

**Comment by reboxer** [comment]
Not sure why this would happen, but im guessing some node versions can't find files if they don't 100% match the file name, what node version are you using?
And could you send the relevant code for this? when you require the module.

**Comment by AugusDogus** [comment]
I had the same error as you did while attempting to dockerize my node app. The issue for me was because my distro of linux is case sensitive in file names so OAuth(.js) is not there, but oauth(.js) is.

**Comment by AugusDogus** [comment]
`const OAuth = require("./lib/OAuth");` should be `const OAuth = require("./lib/oauth");` in `index.js`

**Comment by reboxer** [comment]
pull request merged and released 2.0.2 with this fix
