### ISSUE TITLE
[Enhancement] Export Typings

### ISSUE THREAD

**Issue by WeebHiroyuki** [reboxer/discord-oauth2#53]
I think it'd be quite helpful if the typings for the `User`, `Member`, `Integration`, `Connection`, `Application`, `TokenRequestResult`, and `PartialGuild` interfaces were exported so that they could be reused within my application.

**Comment by reboxer** [comment]
my knowledge of typescript is limited to a simple typings file, if you know how to do it, you are welcome to open a PR to add it.
