### ISSUE TITLE
oauth.addMember nothing is returned when user is in that server

### ISSUE THREAD

**Issue by ririko5834** [reboxer/discord-oauth2#54]
Hi, when I use oauth.addMember and I am on the server, no response is returned in console. There should be returned something, and if the member does not have the roles specifed, they should be given.

**Comment by reboxer** [comment]
That's literally what it says in the README at the bottom of the description of the addMember method: `Returns a member object if the user wasn't part of the guild, else, returns an empty string (length 0).`
