### ISSUE TITLE
Response Invalid JSON

### ISSUE THREAD

**Issue by Krak798** [reboxer/discord-oauth2#61]
**Describe the error**
I tried to log the response that Discord gives me. But it was too much so I decided to log it in a file. But trying to convert the JSON into string with `JSON.stringify()` it outputs this TypeError:
```
(node:20084) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
```

**NodeJS version**
12.18.1

**Relevant code**
```js
try {
        var user = await oauth.getUser(token);

        [...]
    } catch (err) {
        const fs = require("fs");
        fs.writeFileSync("./tmp.log", JSON.stringify(err.res, false, 3));
    }
```

**Comment by reboxer** [comment]
This is completely out of the scope of this library and has nothing to do with it.
Please *read* the [Debugging](https://github.com/reboxer/discord-oauth2#debugging) section of the README, it's clearly stated what properties of the error object to use to get the error message sent by Discord.
It's as easy as adding a catch block to your promises:

```js
.catch((error) => {
        console.log(error.message);
        console.log(error.response);
});
```

**Comment by TheBotlyNoob** [comment]
you could use [flatted](https://www.npmjs.com/package/flatted)
