### ISSUE TITLE
400 Bad Request on POST /api/v7/oauth2/token

### ISSUE THREAD

**Issue by Cat4eve** [reboxer/discord-oauth2#70]
**Describe the error**
I guess I'm doing everything right, I wrote this code 6 months ago and it was working, however, right now something went wrong and I can't figure out

**NodeJS version**
*16.13.1*

**My server.js file**
```js
const koa = require('koa');
const Router = require('@koa/router');
const koaBody = require('koa-body');
const authRouter = require('./routers/authRoute');

const app = new koa();
const router = new Router();

const port = process.env.PORT || 3000;

app.use(koaBody());
app.use(router.routes());
app.use(async (ctx, next) => {
    ctx.set('Access-Control-Allow-Origin', '*');
    ctx.set('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
    ctx.set('Access-Control-Allow-Methods', 'POST, GET, PUT, DELETE, OPTIONS');
    try {
        await next();
    }
    catch(e) {
        console.log(e);
    }
});
app.use(authRouter.routes());
app.use(authRouter.allowedMethods());

app.listen(port, ()=>{console.log(`server is working on port ${port}`)});
```

**My route file**
```js
const client = require('../mongodb');
if (!client) throw new Error('Mongo DB has not been connected.');

const Router = require('@koa/router');
const DiscordOauth2 = require("discord-oauth2");
const cfg = require('../config.json');

const authRouter = new Router();
const oauth = new DiscordOauth2(version = "9");

authRouter.get('/auth/code', async (ctx, next)=>{
    if (ctx.query.code) {
        // Getting the access_token from discord oauth2
        let d = "null";
        oauth.tokenRequest({
            clientId: cfg.botId,
            clientSecret: cfg.clientSecret,
            scope: cfg.scope,
            code: ctx.query.code,
            grantType: "authorization_code",
            redirectUri: `${cfg.redirectUri}/auth/code`
        }).then(data => {d = data; console.log(data)}).catch(err => console.log(err));
        return d;
    }
    ctx.body = JSON.stringify({code: 1, message: 'There is no field named code!'});
    ctx.status = 500;
    return;
});

module.exports = authRouter;
```

**My config.json file**
```js
{
"botId": "secret string",
"clientSecret": "secret string"
"scope": "identify connection guilds",
"redirectUri": "http://localhost:3000/auth/code"
}
```

**Comment by kcinnaydev** [comment]
I'm getting 400 errors as well

**Comment by Cat4eve** [comment]
> I'm getting 400 errors as well

I guess it's because something is wrong on discord server side and such endpoint is no longer available. However the docs in dev portal says that everyhing must be fine.

**Comment by reboxer** [comment]
Currently it works fine for me and i wasn't able to find any complaints in the bot developer servers so i assume it must have been a temporary issue on discord's side.
I recommed you read the [debugging](https://github.com/reboxer/discord-oauth2#debugging) section and set up proper logging for your project with more useful errors.
If the issue still persists please send the more useful messages.

**Comment by Cat4eve** [comment]
@reboxer let me tell you that the module disco-oauth works perfectly well with the same code I provided above, so I guess there is something wrong in your lib.

**Comment by reboxer** [comment]
> @reboxer let me tell you that the module disco-oauth works perfectly well with the same code I provided above, so I guess there is something wrong in your lib.

Like i said, it works perfectly fine for me, and no changes have been made to the way requests are made or to the `tokenRequest` function, so this may be an issue with the way you handle the requests and you are not handling correctly each of them. Unless you provide the proper error messages to debug this issue, there is nothing i can help you with.

**Comment by nesttle** [comment]
Same issue here

`(node:11404) UnhandledPromiseRejectionWarning: DiscordHTTPError: 400 Bad Request on POST /api/v7/oauth2/token`

**Comment by Cat4eve** [comment]
> Same issue here
> 
> `(node:11404) UnhandledPromiseRejectionWarning: DiscordHTTPError: 400 Bad Request on POST /api/v7/oauth2/token`

For me disco-oauth library worked fine.

**Comment by nesttle** [comment]
Fixed, my problem was an invalid `redirectUri`!

**Comment by Cat4eve** [comment]
> Fixed, my problem was an invalid `redirectUri`!

A bit strange cuz i used the same settings bit this library showed an error.
