### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by KingCh1ll** [reboxer/discord-oauth2#71]
**Describe the error**
The callback never works. It just goes on a loop of loading.

**NodeJS version**
v16.6

**Library version**
v2.9.0

**Error stack and exact error message**
No error, it just freezes and never goes though.

**Relevant code**
```js
const Express = require("express");
const DiscordAuth = require("discord-oauth2");

const config = require("../../globalconfig.json")
const scopes = ["identify", "guilds"]

const Router = Express.Router();
const auth = new DiscordAuth({
    clientId: config.client_ID,
    clientSecret: process.env.SECRET,
    redirectUri: encodeURIComponent(config.redirectURL)
});

Router.get("/", async (request, response) => {
  const code = request.query.code;

  if (!code) return response.redirect("/?error=NoCodeReturned")

  console.log(code)

  let data, userData, guildData;

    try {
        data = await auth.tokenRequest({
            code,
            scope: scopes.join(' '),
            grantType: "authorization_code",
        }).then(data => console.log(data));
    }catch(err){
      console.error(err)

      return response.redirect('/?error='+err.message);
    }

  console.log(data);
});
```

**Comment by KingCh1ll** [comment]
I debugged it and it seems it gets stuck on the `auth.tokenRequest()` function.

**Comment by reboxer** [comment]
not a library issue
```js
  const code = request.query.code;

  if (!code) return response.redirect("/?error=NoCodeReturned")
```
you are checking if the querystring contains `code` and when it's not there you just keep redirecting to the exact same path (without `code`) and cause an infinite redirect loop

![NVIDIA_Share_0uPY0lSzrt](https://user-images.githubusercontent.com/7484116/151843777-f65bd7da-ca2b-4cd3-95eb-77d17b4af909.png)
![NVIDIA_Share_d1pzurcnxT](https://user-images.githubusercontent.com/7484116/151843625-25a95237-3516-463e-a3e8-c5e7987579c7.png)

-------------------------

```js
    redirectUri: encodeURIComponent(config.redirectURL)
```
there is no need to encode the redirect URI, discord doesn't like this and the request will fail

-------------------------

```js
            scope: scopes.join(' '),
```
`tokenRequest` accepts an array of scopes, `scopes` is already an array, no need to make it an string

**Comment by KingCh1ll** [comment]
Thank you!
