### ISSUE TITLE
getGuildMember takes years.

### ISSUE THREAD

**Issue by imalfect** [reboxer/discord-oauth2#76]
oauth.getGuildMember sometimes gets stuck and takes years, sometimes it works instantly but sometimes it's getting stuck.

**Comment by sofianeOuafir** [comment]
Have you been able to solve this?

**Comment by imalfect** [comment]
> Have you been able to solve this?

Hi yes, as reboxer stater before it had an aggressive rate limit, I recommend totally avoiding using this function and using a discord bot invited on that server to get such information

**Comment by elie222** [comment]
Interesting it even works for you. I get 401 errors on this endpoint.
