### ISSUE TITLE
AddMember Giving Discord API error

### ISSUE THREAD

**Issue by 830008** [reboxer/discord-oauth2#77]
**Describe the error**
I am getting a discord API error.

**NodeJS version**
*LTS*

**Library version**
*Latest*

**Error stack and exact error message**
APIError: [4/10/2022, 9:38:51 PM] :: Discord API Error encountered.
undefined

    at C:\Users\nroll\Desktop\Development\JavaScript\DjsV13Testing - Copy (2)\node_modules\disco-oauth\lib\client.js:228:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Relevant code**
```js
discordauth.addMember({
                        accessToken: AccessToken,
                        botToken: "Removed",
                        guildId: interaction.guild.id,
                        userId: User.id
                    })
```

**Comment by Spyynz** [comment]
was this ever fixed?
