### ISSUE TITLE
Error while using "getUser(AccesToken)"

### ISSUE THREAD

**Issue by Burchard36** [reboxer/discord-oauth2#8]
I have a simple SocketIO server setup from my panel that passes an `AccessToken` to authenticate on a panel I am making. The token is passed successfully however i get a `DiscordHTTPError: 401 UNAUTHORIZED on GET /api/v7/users/@me` When using `discord-oauth2#getUser(AccessToken)`

The current system i have setup is simple (Pretty much copy/pasted from README.md)

```javascript
const io = require('socket.io').listen(3001);
const Discord = require('discord-oauth2');
const oauth2 = new Discord();

io.on('connection', (socket) => {
    socket.on('authenticate', (data) => {
        if (data === undefined) {
            socket.emit('failed', 'The token provided was not valid.');
        } else {
            console.log(data); // This logs the access token i have, so i know its passess successfully
            oauth2.getUser(data).then(console.log).catch(err => {
                console.log(err.response);
            });
        }
    })
});
```

Logging just the `err` produces this stack:
```brainfuck
DiscordHTTPError: 401 UNAUTHORIZED on GET /api/v7/users/@me
    at OAuth.request (C:\Users\Dalton\Desktop\TicketManager Panwl\node_modules\discord-oauth2\lib\eris\rest\RequestHandler.js:90:15)
    at OAuth.getUser (C:\Users\Dalton\Desktop\TicketManager Panwl\node_modules\discord-oauth2\lib\oauth.js:85:21)
    at Socket.<anonymous> (C:\Users\Dalton\Desktop\TicketManager Panwl\index.js:31:20)
    at Socket.emit (events.js:210:5)
    at C:\Users\Dalton\node_modules\socket.io\lib\socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

Console logging `err.response` Produces this JSON Object:
```
{ message: '401: Unauthorized', code: 0 }
```

Am i doing something wrong here or is this an issue on the library/discord's side?

**Comment by Burchard36** [comment]
![image](https://user-images.githubusercontent.com/48583030/74302334-07db1a00-4d0b-11ea-82b3-4905b204dbb3.png)

I am using the OAuth link generated by this OAuth option by the way (Didnt know if that had an issue with it? left it here in case)

**Comment by reboxer** [comment]
How are you getting the access token? are you passing to `getUser()` the code discord sends you in the redirect after you authorize the application?
if that's the case, you have to use that code with [tokenRequest](https://github.com/reboxer/discord-oauth2/blob/master/README.md#tokenrequest) which will return the correct access token you use to request user data.

**Comment by Burchard36** [comment]
Ah okay i had assumed for whatever reason i did not need tokenRequest if i was simply grabbing the user object, got it working and thank you very much! Thanks for the fast response as well :)
