### ISSUE TITLE
DiscordHTTPError: 400 Bad Request on POST /api/v9/oauth2/token

### ISSUE THREAD

**Issue by sharaalt** [reboxer/discord-oauth2#95]
**Describe the error**
I'm trying to run my code and it return's an error here is the code and error.

**NodeJS version**
*v16.17.1.*

**Library version**
*Latest*

**Error stack and exact error message**
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

DiscordHTTPError: 400 Bad Request on POST /api/v9/oauth2/token

**Relevant code**
```js
const DiscordOauth2 = require("discord-oauth2");
const oauth = new DiscordOauth2();


oauth.tokenRequest({
	clientId: "1097682671238398162",
	clientSecret: "youshouldntseeit",


	scope: "identify guilds",
	grantType: "authorization_code",

	redirectUri: "https://pro-moderation.theeuphoniumking.repl.co/servers.html",
}).then(console.log)

```

**Comment by angelxmoreno** [comment]
I am still getting this error. what was the fix/resolution?

**Comment by angelxmoreno** [comment]
nvm. The error isn't from `discord-oauth2`. resolved and all is great.

**Comment by zlyfer** [comment]
> nvm. The error isn't from `discord-oauth2`. resolved and all is great.

How did you resolve this error?
